baseURL = "https://brunorosilva.github.io/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "education"
  URL = "#education"
  weight = 4

  [[menu.header]]
  name = "work"
  URL = "#experience"
  weight = 2

  [[menu.header]]
  name = "projects"
  URL = "#portfolio"
  weight = 3


  [[menu.footer]]
  name = "education"
  URL = "#education"
  weight = 2

  [[menu.footer]]
  name = "work"
  URL = "#experience"
  weight = 3

  [[menu.footer]]
  name = "projects"
  URL = "#portfolio"
  weight = 4


[params]

  sections = ["showcase", "about", "experience", "client-and-work", "education", "testimonial", "contact", "newsletter"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = ""
    text2 = "chicelli"

  [params.footer]
      copyright = "© Bruno Chicelli. See the code for this page"
      projectCodeName = "here"
      projectCodeURL = "https://github.com/brunorosilva/brunorosilva.github.io"
